### PR TITLE
Test directly on Python 3.5.2

### PR DESCRIPTION
**Pull request by mitar**
Python 3.5.2 is default on current LTS Ubuntu.

### CODE REVIEW

**Comment by mitar** [comment]
See #5.

**Comment by mitar** [comment]
It is failing on 3.5.2 and even 3.6-dev.

**Comment by ilevkivskyi** [comment]
The failure on 3.6-dev is expected, we still have two-three weeks to fix this (this is straightforward, all calls to ``_gorg`` should be just replaced with attribute access, see https://github.com/python/cpython/pull/3550). Fixing 3.5.2 will be more difficult however, since the internal ``typing`` API is different.

**Comment by mitar** [comment]
In the code there is this [note](https://github.com/ilevkivskyi/typing_inspect/blob/master/typing_inspect.py#L8) about requirement to support both 2.7 and 3.x. Is this still the goal? It would be great if it was. :-)

**Comment by ilevkivskyi** [comment]
> In the code there is this note about requirement to support both 2.7 and 3.x. Is this still the goal? It would be great if it was. :-)

I don't understand what you are pushing here. If you want support on more versions I will gladly consider your PR that actually adds such support.

**Comment by mitar** [comment]
My question here is: what is current design goal. Code says "2.7 and 3.x" while README says "Works with typing version 3.6.1 and later." So is support for older versions something you, as a maintainer, would like and is just a problem of fixing those, so PRs are welcome, or are old versions out of the scope? This is what I asked. Not sure why you just closed this PR because it could be a based for adding 3.5.2 support.

**Comment by ilevkivskyi** [comment]
> So is support for older versions something you, as a maintainer, would like and is just a problem of fixing those, so PRs are welcome, or are old versions out of the scope?

The ``typing`` version and Python version are different things. The goal is to support both Python 2.7 and Python 3.x (for all x) where ``typing`` _package_ version 3.6.1+ is installed. For Python versions 3.5 and 3.6 this poses some problems, since stdlib modules take precedence over installed. Therefore, for these Python versions only the latest Python bugfix version in the corresponding branch is supported. If anyone wants support of previous Python bugfix releases, PRs are very welcome (but it is unlikely that I will do this myself).

>  Not sure why you just closed this PR because it could be a based for adding 3.5.2 support.

I don't want to separate PRs with the support and the test setup updates. Ideally I would prefer these to be in the same PR.

**Comment by mitar** [comment]
Yes, the idea is to update this PR. :-)

I just pushed a fix for `Union`. But the issue is now in `ClassVar`. It seems 3.5.2 simply does not have that. So I do not see how this package could support 3.5.2?

Is there a way to force the use of a package over the stdlib?

**Comment by ilevkivskyi** [comment]
> Is there a way to force the use of a package over the stdlib?

One can copy the installed file directly but this is too dirty. So basically the answer is no.

> So I do not see how this package could support 3.5.2?

``is_classvar`` can just raise an exception if called on this version. Other possible option is to have ``typing_extensions`` as an optional dependency via ``try: from typing_extensions import ClassVar ...``.

**Comment by mitar** [comment]
`is_classvar` is used in many other functions inside this package, so exception might propagate a lot. :-(

I think I will go with `typing_extensions` approach.

**Comment by mitar** [comment]
I added commits using `typing_extensions` to address imports. But there are now many more other tests failing. :-(

**Comment by mitar** [comment]
I think I am giving up. This is too much difference.

**Pull request closed without merging**
