### PR TITLE
NewType recognises custom implementations

### PR DESCRIPTION
**Pull request by gabor-akeero**
See [issue #91](https://github.com/ilevkivskyi/typing_inspect/issues/91)

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
FWIW the current behavior is intentional, see original PR https://github.com/ilevkivskyi/typing_inspect/pull/78, but maybe the qualified name check is enough. On the added `isinstance(..., type)` will this work for nested `NewType`s? For example `UserId = NewType("UserId", int); LegacyUserId = NewType("LegacyUserId", UserId)`? Btw it looks like our current test case for this is broken (there is a missing trailing underscore in the nested call `NewType_('F', NewType('F_', int))`)

Oh and also for some reason Travis build didn't start. It looks like it is time to switch to GitHub actions.

**Comment by gabor-akeero** [comment]
You're right, those `NewType`-s aren't recognised :( , I need to dive into that...

**Comment by gabor-akeero** [comment]
Meanwhile the issue has been fixed on `marshmallow_dataclass` side.

**Comment by ilevkivskyi** [comment]
Glad to hear it was fixed!

**Pull request closed without merging**
