### PR TITLE
Make `get_origin(Literal[...]) == Literal`.

### PR DESCRIPTION
**Pull request by anntzer**
See https://github.com/ilevkivskyi/typing_inspect/pull/39#issuecomment-907637313.

### CODE REVIEW

**Review by ilevkivskyi — APPROVED** [review]

**Comment by ilevkivskyi** [comment]
Hm, it looks like some tests failed. Could you please fix them before I can merge this?

**Comment by anntzer** [comment]
Looks like(?) the failure now arises because of the confusion between typing.Literal (the backport of typing) and typing_extension.Literal.  Not sure what the best approach is here...

**Comment by anntzer** [comment]
Now fixed.  There are some other failures, but they are unrelated to this PR (see e.g. #84).

**Comment by ilevkivskyi** [comment]
It looks like there are two other failures because new `pytest` doesn't support Python 3.5.0 and 3.5.1. Probably we can just stop testing those (so support will be best effort).

Could you please make a separate PR updating typing_extension requirement and test matrix for Python versions?

**Comment by ilevkivskyi** [comment]
Or actually you mean the issue is still present even on latest `typing_extensions`? If yes, we will need to investigate. (But you can still make a PR for not testing Python versions if you still have time for this.)

**Comment by anntzer** [comment]
The failure of tests with Python 3.5.{0,1} is easy to fix so I did that at #85.
There's another test failure revolving around TypedDict with python 3.9.12, for which I don't have a quick fix (but which, I'd argue, should not block this PR as it is also completely unrelated).

**Comment by ilevkivskyi** [comment]
OK, I will merge this now, and will look at the remaining failure later.

**Pull request merged**
